version: '3.8'

services:
  dashboard:
    build: .
    container_name: billing_dashboard
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "80:8501"
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo

  worker:
    build: .
    container_name: billing_worker
    command: python -u scheduler.py
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo

  grafana:
    image: grafana/grafana-oss:latest
    container_name: billing_grafana
    network_mode: "host"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - TZ=America/Sao_Paulo
    volumes:
      - sqlite_data:/app/data
      - grafana_data:/var/lib/grafana
    restart: unless-stopped 

volumes:
  sqlite_data:
  grafana_data: