services:
  worker:
    build: .
    container_name: billing_worker
    network_mode: "host"
    command: python -u scheduler.py
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo